# backend/app/services/document_service.py - FINAL, INTELLIGENT VERSION

from docx import Document
from pptx import Presentation
from pptx.util import Inches
from typing import List
import io

# A simple data structure for passing section data
class SectionData:
    def __init__(self, title: str, content: str):
        self.title = title
        self.content = content

# --- Document Creation for Microsoft Word (unchanged) ---
def create_word_document(sections: List[SectionData]) -> io.BytesIO:
    document = Document()
    # Assuming the first section title is the main document title
    document.add_heading(sections[0].title if sections else "Generated Document", level=1)

    for section in sections:
        document.add_heading(section.title, level=2)
        document.add_paragraph(section.content)
        document.add_page_break()

    file_stream = io.BytesIO()
    document.save(file_stream)
    file_stream.seek(0)
    return file_stream

# --- Helper Function for Intelligent Text Splitting ---
def _split_text_into_chunks(text: str, max_chars: int) -> List[str]:
    """
    Intelligently splits a long string into smaller chunks under a max character
    limit, without splitting words.
    """
    if not text:
        return []

    words = text.split()
    chunks = []
    current_chunk = ""

    for word in words:
        # Check if adding the next word exceeds the limit
        if len(current_chunk) + len(word) + 1 > max_chars:
            # If the chunk is not empty, add it to the list
            if current_chunk:
                chunks.append(current_chunk.strip())
            current_chunk = word
        else:
            # Add the word to the current chunk
            if current_chunk:
                current_chunk += " " + word
            else:
                current_chunk = word
    
    # Add the last remaining chunk
    if current_chunk:
        chunks.append(current_chunk.strip())
        
    return chunks

# --- NEW, INTELLIGENT PowerPoint Creation ---
def create_powerpoint_presentation(sections: List[SectionData]) -> io.BytesIO:
    prs = Presentation()
    title_slide_layout = prs.slide_layouts[0]
    content_slide_layout = prs.slide_layouts[1]

    # This is now a guideline for the maximum characters per slide body.
    # 650-750 is a good starting point for a standard presentation font size.
    MAX_CHARS_PER_SLIDE = 450

    # Create the main title slide
    if sections:
        slide = prs.slides.add_slide(title_slide_layout)
        title = slide.shapes.title
        subtitle = slide.placeholders[1]
        # We'll use the project title for the main slide, assuming the first section is part of the content.
        title.text = sections[0].title 
        subtitle.text = "Generated by AI Document Platform"

    # Intelligently loop through each section
    for section in sections:
        # Use our new helper function to split the content into perfectly sized chunks
        content_chunks = _split_text_into_chunks(section.content, MAX_CHARS_PER_SLIDE)
        
        # If there's no content for a section, create a single slide with just the title
        if not content_chunks:
            slide = prs.slides.add_slide(content_slide_layout)
            slide.shapes.title.text = section.title
            slide.shapes.placeholders[1].text = "[No content for this section]"
            continue

        # Loop through the generated chunks and create a slide for each one
        is_first_slide_for_section = True
        for chunk in content_chunks:
            slide = prs.slides.add_slide(content_slide_layout)
            title = slide.shapes.title
            body = slide.shapes.placeholders[1]
            
            # Set the slide title, adding "(Cont.)" for continuation slides
            if is_first_slide_for_section:
                title.text = section.title
                is_first_slide_for_section = False
            else:
                title.text = f"{section.title} (Cont.)"
            
            # Add the chunk of text to the slide
            body.text = chunk

    file_stream = io.BytesIO()
    prs.save(file_stream)
    file_stream.seek(0)
    return file_stream