
from docx import Document
from pptx import Presentation
from pptx.util import Inches
from typing import List
import io

class SectionData:
    def __init__(self, title: str, content: str):
        self.title = title
        self.content = content

def create_word_document(sections: List[SectionData]) -> io.BytesIO:
    document = Document()
    document.add_heading(sections[0].title if sections else "Generated Document", level=1)

    for section in sections:
        document.add_heading(section.title, level=2)
        document.add_paragraph(section.content)
        document.add_page_break()

    file_stream = io.BytesIO()
    document.save(file_stream)
    file_stream.seek(0)
    return file_stream

def _split_text_into_chunks(text: str, max_chars: int) -> List[str]:
    """
    Intelligently splits a long string into smaller chunks under a max character
    limit, without splitting words.
    """
    if not text:
        return []

    words = text.split()
    chunks = []
    current_chunk = ""

    for word in words:
        if len(current_chunk) + len(word) + 1 > max_chars:
            if current_chunk:
                chunks.append(current_chunk.strip())
            current_chunk = word
        else:
            if current_chunk:
                current_chunk += " " + word
            else:
                current_chunk = word
    
    if current_chunk:
        chunks.append(current_chunk.strip())
        
    return chunks


def create_powerpoint_presentation(sections: List[SectionData]) -> io.BytesIO:
    prs = Presentation()
    title_slide_layout = prs.slide_layouts[0]
    content_slide_layout = prs.slide_layouts[1]

    MAX_CHARS_PER_SLIDE = 450

    if sections:
        slide = prs.slides.add_slide(title_slide_layout)
        title = slide.shapes.title
        subtitle = slide.placeholders[1]
        title.text = sections[0].title 
        subtitle.text = "Generated by AI Document Platform"

    for section in sections:
        content_chunks = _split_text_into_chunks(section.content, MAX_CHARS_PER_SLIDE)
        
        if not content_chunks:
            slide = prs.slides.add_slide(content_slide_layout)
            slide.shapes.title.text = section.title
            slide.shapes.placeholders[1].text = "[No content for this section]"
            continue

        is_first_slide_for_section = True
        for chunk in content_chunks:
            slide = prs.slides.add_slide(content_slide_layout)
            title = slide.shapes.title
            body = slide.shapes.placeholders[1]
            if is_first_slide_for_section:
                title.text = section.title
                is_first_slide_for_section = False
            else:
                title.text = f"{section.title} (Cont.)"
            
            body.text = chunk

    file_stream = io.BytesIO()
    prs.save(file_stream)
    file_stream.seek(0)
    return file_stream